### ISSUE TITLE
EXPLAIN FORMAT Does Not Work

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#114]
Submitted by David E.Wheeler, 2014-02-24.

See [sourceforge bug tracker](https://sourceforge.net/p/postgres-xc/bugs/482/) for details.

Create a table, insert a couple of rows, then EXPLAIN a query run against it:

```
% psql -c 'CREATE TABLE foo (id int); INSERT INTO foo VALUES (1), (2);'
INSERT 0 2
% psql -c 'EXPLAIN select count(*) from foo'
                                      QUERY PLAN                                       
---------------------------------------------------------------------------------------
 Aggregate  (cost=2.50..2.51 rows=1 width=0)
   ->  Data Node Scan on "__REMOTE_GROUP_QUERY__"  (cost=0.00..0.00 rows=1000 width=0)
         Node/s: rptdata01, rptdata02, rptdata03, rptdata04
So far so good. Now ask for another explain format:
% psql -c 'EXPLAIN (FORMAT YAML) select count(*) from foo'
connection to server was lost
Oy. The log for my coordinator looks like this:
2014-02-24 11:56:41 PST   22325 530659c2.5735 LOG:  server process (PID 772) was terminated by signal 11: Segmentation fault
2014-02-24 11:56:41 PST   22325 530659c2.5735 DETAIL:  Failed process was running: EXPLAIN (FORMAT YAML) select count(*) from foo
2014-02-24 11:56:41 PST   22325 530659c2.5735 LOG:  terminating any other active server processes
2014-02-24 11:56:41 PST   610 530ba39c.262 WARNING:  terminating connection because of crash of another server process
2014-02-24 11:56:41 PST   610 530ba39c.262 DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2014-02-24 11:56:41 PST   610 530ba39c.262 HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2014-02-24 11:56:41 PST   22325 530659c2.5735 LOG:  all server processes terminated; reinitializing
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  database system was interrupted; last known up at 2014-02-24 11:55:08 PST
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  database system was not properly shut down; automatic recovery in progress
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  redo starts at 0/2D4A788
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  record with zero length at 0/2D4A7E8
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  redo done at 0/2D4A7B8
2014-02-24 11:56:41 PST   774 530ba3f9.306 LOG:  last completed transaction was at log time 2014-02-24 19:56:08.535355+00
2014-02-24 11:56:41 PST   778 530ba3f9.30a LOG:  autovacuum launcher started
2014-02-24 11:56:41 PST   22325 530659c2.5735 LOG:  database system is ready to accept connections
```

Nothing appears in the logs for any other data node or coordinator.

**Comment by scarbrofair** [comment]
I can reproduce it with latest code. I create a ticket to fix this issue, and it works:

```
[pgsql@localhost bin]$ ./psql -d postgres -p 15434
psql (PGXC 1.3devel, based on PG 9.4beta1)
Type "help" for help.

postgres=# EXPLAIN (FORMAT YAML) select count(*) from foo;
                     QUERY PLAN                     
----------------------------------------------------
 - Plan:                                           +
     Node Type: "Aggregate"                        +
     Strategy: "Plain"                             +
     Startup Cost: 2.50                            +
     Total Cost: 2.51                              +
     Plan Rows: 1                                  +
     Plan Width: 0                                 +
     Plans:                                        +
       - Node Type: "Data Node Scan"               +
         Parent Relationship: "Outer"              +
         RemoteQuery name: "__REMOTE_GROUP_QUERY__"+
         Alias: "__REMOTE_GROUP_QUERY__"           +
         Startup Cost: 0.00                        +
         Total Cost: 0.00                          +
         Plan Rows: 1000                           +
         Plan Width: 0                             +
         Node/s: "dn1, dn2"
(1 row)

postgres=# \q
```

This issue will core down the datanode and coordinator. Because it use an variable named sname of char *, but X2 does not initialize it or assign it with a valid memory address. For detail please check  ExplainNode() of  src/backend/commands/explain.c. Follow is the core down stack:

```
(gdb) bt
#0  0x00000000006b0c14 in escape_json (buf=0x2246e40, str=<optimized out>) at json.c:1795
#1  0x000000000053ceda in escape_yaml (str=<optimized out>, buf=<optimized out>) at explain.c:2741
#2  ExplainProperty (qlabel=qlabel@entry=0x83c10f "Node Type", value=value@entry=0x290 <Address 0x290 out of bounds>, 
    numeric=numeric@entry=0 '\000', es=es@entry=0x7fff9a5bca30) at explain.c:2297
#3  0x000000000053f2c4 in ExplainPropertyText (es=0x7fff9a5bca30, value=0x290 <Address 0x290 out of bounds>, 
    qlabel=0x83c10f "Node Type") at explain.c:2308
#4  ExplainNode (planstate=0x2364870, ancestors=0x2364870, ancestors@entry=0x2362798, 
    relationship=relationship@entry=0x83c49f "Outer", plan_name=plan_name@entry=0x0, es=es@entry=0x7fff9a5bca30) at explain.c:1013
#5  0x000000000053e55b in ExplainNode (planstate=0x2363f40, ancestors=0x2362798, ancestors@entry=0x0, 
    relationship=relationship@entry=0x0, plan_name=plan_name@entry=0x0, es=es@entry=0x7fff9a5bca30) at explain.c:1539
#6  0x000000000053fc1b in ExplainPrintPlan (es=es@entry=0x7fff9a5bca30, queryDesc=queryDesc@entry=0x2362648) at explain.c:574
#7  0x000000000053fe06 in ExplainOnePlan (plannedstmt=<optimized out>, into=<optimized out>, es=0x7fff9a5bca30, 
    queryString=0x22f8ab0 "EXPLAIN (FORMAT YAML) select count(*) from foo;", params=0x0) at explain.c:495
#8  0x0000000000540478 in ExplainQuery (stmt=stmt@entry=0x22f9908, 
    queryString=queryString@entry=0x22f8ab0 "EXPLAIN (FORMAT YAML) select count(*) from foo;", params=params@entry=0x0, 
    dest=0x2246e70) at explain.c:234
#9  0x000000000066d441 in standard_ProcessUtility (parsetree=0x22f9908, 
    queryString=0x22f8ab0 "EXPLAIN (FORMAT YAML) select count(*) from foo;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    dest=<optimized out>, sentToRemote=<optimized out>, completionTag=0x7fff9a5bcc50 "") at utility.c:976
#10 0x00000000006693cb in PortalRunUtility (portal=portal@entry=0x2353dc0, utilityStmt=0x22f9908, isTopLevel=<optimized out>, 
    dest=dest@entry=0x2246e70, completionTag=completionTag@entry=0x7fff9a5bcc50 "") at pquery.c:1285
#11 0x000000000066a20d in FillPortalStore (portal=portal@entry=0x2353dc0, isTopLevel=isTopLevel@entry=1 '\001') at pquery.c:1155
#12 0x000000000066ac1f in PortalRun (portal=portal@entry=0x2353dc0, count=count@entry=9223372036854775807, 
    isTopLevel=isTopLevel@entry=1 '\001', dest=dest@entry=0x22f9e20, altdest=altdest@entry=0x22f9e20, 
    completionTag=completionTag@entry=0x7fff9a5bcf00 "") at pquery.c:851
#13 0x0000000000668901 in exec_simple_query (query_string=0x22f8ab0 "EXPLAIN (FORMAT YAML) select count(*) from foo;")
    at postgres.c:1153
#14 PostgresMain (argc=<optimized out>, argv=argv@entry=0x222d9f8, dbname=0x222d8a8 "postgres", username=<optimized out>)
    at postgres.c:4245
#15 0x0000000000461c3f in BackendRun (port=0x2250810) at postmaster.c:4270
#16 BackendStartup (port=0x2250810) at postmaster.c:3959
---Type <return> to continue, or q <return> to quit---
#17 ServerLoop () at postmaster.c:1709
#18 0x00000000006280bc in PostmasterMain (argc=argc@entry=4, argv=argv@entry=0x222b9d0) at postmaster.c:1368
#19 0x00000000004625fd in main (argc=4, argv=0x222b9d0) at main.c:196
```

And the ticket is simple. Please modify the 915 line of src/backend/commands/explain.c as following:

```
            pname = sname = "Data Node Scan";
```

**Comment by koichi-szk** [comment]
Thank you very much for the report and the fix.   It was committed as:

master: 61bfb57398e4629efe059c9df17e3d6df5be118b
REL1_2_STABLE: 6bc4e3db2347c82076440315e8db9c62a83fe1ff
REL1_1_STABLE: d5b960ba69a0e564c6cc61c628e54f2e1f6e4a72
