### ISSUE TITLE
If handling HandlePoolerReload signature needs section protection?

### ISSUE THREAD

**Issue by neoqguo** [postgres-x2/postgres-x2#299]
When Primary datanode fails, failover is successful. ALTER NODE and pgxc_pool_reload is issued to reflect cluster topology change,
then, backend would be interrupted to handle sigusr1, it would rollback current transaction and clear relative resource, such as CurrentResourceOwner,
after that, backend gose on. While, we meet the problem like the stack below. 
If we need to hold sigusr1 until CommitTransactionCommand finished, OR, use another signal to handle pgxc_pool_reload action.

Look forward to receiving your reply.
Regards~

---

Program terminated with signal 11, Segmentation fault.
#0  0x00000000008d9f64 in ResourceOwnerReleaseInternal (owner=0x0, phase=RESOURCE_RELEASE_BEFORE_LOCKS, isCommit=1 '\001', isTopLevel=1 '\001') at resowner.c:268

268     resowner.c: 没有那个文件或目录.
        in resowner.c
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.tl1.5.x86_64
(gdb) bt
#0  0x00000000008d9f64 in ResourceOwnerReleaseInternal (owner=0x0, phase=RESOURCE_RELEASE_BEFORE_LOCKS, isCommit=1 '\001', isTopLevel=1 '\001') at resowner.c:268
#1  0x00000000008d9ef7 in ResourceOwnerRelease (owner=0x0, phase=RESOURCE_RELEASE_BEFORE_LOCKS, isCommit=1 '\001', isTopLevel=1 '\001') at resowner.c:246
#2  0x00000000004d4c8e in CommitTransaction () at xact.c:2428
#3  0x00000000004d5a4a in CommitTransactionCommand () at xact.c:3281
#4  0x000000000078d1d3 in finish_xact_command () at postgres.c:2570
#5  0x000000000078f8f0 in PostgresMain (argc=1, argv=0x7fbe3fcb7e10, dbname=0x7fbe3fcb7c48 "postgres", username=0x7fbe3fcb7c28 "postgres") at postgres.c:4596
#6  0x0000000000728265 in BackendRun (port=0x19c2360) at postmaster.c:4586
#7  0x000000000072786f in BackendStartup (port=0x19c2360) at postmaster.c:4212
#8  0x0000000000723d8f in ServerLoop () at postmaster.c:1820
#9  0x0000000000723551 in PostmasterMain (argc=5, argv=0x19a7480) at postmaster.c:1472
#10 0x000000000068439c in main (argc=5, argv=0x19a7480) at main.c:196

---

**Comment by neoqguo** [comment]
And it may try to rollback a commited transaction, that would cause abort.
